language: minimal

jobs:
  - os: linux
    env: BUILD_IMAGE=archlinux
  - os: osx
    osx_image: xcode11.3

services:
  - docker

archlinux:
  packages:
    - python-pip
  mount:
    - ~/.pkg-cache:/var/cache/pacman/pkg
  before_install:
      - PATH="$PATH:$HOME/.local/bin"
  script:
    - pacman --version
    - pip install ansible
    - bash ./test/test.sh

script:
    - if [ "${BUILD_IMAG-}" = archlinux ]; then
      - curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash
    - else
      - bash ./test/test.sh
    - fi

