language: minimal

os: linux

services:
  - docker
archlinux:
  packages:
    - python
  mount:
    - ~/.pkg-cache:/var/cache/pacman/pkg
  script:
    - pip install ansible
    - ansible --version
    - ansible --version
    - ansible-playbook --syntax-check ./main.yml -i ./inventory
    - ansible-playbook ./main.yml -i ./inventory

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

