language: minimal

os: osx
osx_image: xcode11.3

install:
  - pip intsll ansible

before_script:
  - ansible --version

script:
  - ansible-playbook --syntax-check ./main.yml -i ./inventory
  - ansible-playbook ./main.yml -i ./inventory
