language: minimal

os: linux

services:
  - docker
archlinux:
  packages:
    - python
  mount:
    - ~/.pkg-cache:/var/cache/pacman/pkg
  before_install:
    - "sudo ln -s /dev/null /etc/pacman.d/hooks/package-cleanup.hook"

install:
  - pip install ansible

before_script:
  - ansible --version

script:
  - ansible-playbook --syntax-check ./main.yml -i ./inventory
  - ansible-playbook ./main.yml -i ./inventory
