language: minimal

os: linux

services:
  - docker
archlinux:
  packages:
    - python
  mount:
    - ~/.pkg-cache:/var/cache/pacman/pkg
  before_install:
    - "sudo ln -s /dev/null /etc/pacman.d/hooks/package-cleanup.hook"
  script:
    - "uname -a"
    - "pwd"
    - "ls -al"

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
  - "uname -a"
  - "pwd"
  - "ls -al"
